---
# Debian PPA repositories

# The GPG keys for the PPA repos, provide the URL to get the GPG keys from and the keys

gpg_keys:
  - package: ha-proxy
    url: https://pks.haproxy.com/linux/community/RPM-GPG-KEY-HAProxy
    dest: /etc/apt/keyrings/HAPROXY-key-community.asc

ppa_repos:
  - "deb [signed-by=/etc/apt/keyrings/HAPROXY-key-community.asc] https://www.haproxy.com/download/haproxy/performance/ubuntu/ha33 {{ ansible_distribution_release | lower}}  main"

debian_packages:
  - git
  - haproxy
  - python3-pip
  - python3-flask
  - python3-markdown
  - pylint
  - vim
  - nginx

